version: '3'
services:
  fantasy_server:
    env_file: .test.env
    build:
      context: ./server
      dockerfile: test.Dockerfile
    container_name: fantasy_server
    ports:
      - "3000:3000"
    volumes:
      - ${HOST_DATA_DIR}:/data/fantasy_server
    depends_on:
      - "redis"
      - "mariadb"
  redis:
    env_file: .test.env
    image: redis:alpine
  mariadb:
    env_file: .test.env
    image: mariadb:bionic